language: ruby
sudo: false
branches:
  only:
    - rewrite

rvm:
   - 2.0.0
   - 2.1.7
   - 2.2.3

env:
  global:
  - PLUGIN=redmine_chronos
  - REDMINE=test_redmine

  matrix:
  - REDMINE_VERSION=2.4.0 TRACE=--trace
  - REDMINE_VERSION=2.4.5 TRACE=--trace
  - REDMINE_VERSION=2.5.3 TRACE=--trace
  - REDMINE_VERSION=2.6.3 TRACE=--trace
  - REDMINE_VERSION=2.6.4 #TRACE=--trace bugged for this version
  - REDMINE_VERSION=2.6.6 #TRACE=--trace bugged for this version
  - REDMINE_VERSION=3.0.4 TRACE=--trace
  - REDMINE_VERSION=3.1.0 TRACE=--trace

matrix:
  exclude:
  # Redmine before 2.6.6 will not run on Ruby 2.2
  - rvm: 2.2.3
    env: REDMINE_VERSION=2.4.0 TRACE=--trace
  - rvm: 2.2.3
    env: REDMINE_VERSION=2.4.5 TRACE=--trace
  - rvm: 2.2.3
    env: REDMINE_VERSION=2.5.3 TRACE=--trace
  - rvm: 2.2.3
    env: REDMINE_VERSION=2.6.3 TRACE=--trace
  - rvm: 2.2.3
    env: REDMINE_VERSION=2.6.4 #TRACE=--trace bugged for this version
  # Redmine before 2.5 will not run on Ruby 2.1
  - rvm: 2.1.7
    env: REDMINE_VERSION=2.4.0 TRACE=--trace
  - rvm: 2.1.7
    env: REDMINE_VERSION=2.4.5 TRACE=--trace

before_install:
- . .travis/clone_redmine.sh

gemfile: test_redmine/Gemfile
install:
- cd $PATH_TO_REDMINE
- bundle install --jobs=3 --retry=3 --path=$PATH_TO_PLUGIN/vendor/bundle
- bundle exec rake $TRACE db:migrate
- bundle exec rake $TRACE redmine:load_default_data REDMINE_LANG=en
- bundle exec rake $TRACE $GENERATE_SECRET
- bundle exec rake $TRACE $MIGRATE_PLUGINS

script:
- cd $PATH_TO_REDMINE
- if [ "$TRACE" == "--trace" ]; then export BACKTRACE=--backtrace; fi
- if [ -z "$TRACE" ]; then unset BACKTRACE; fi
- bundle exec rspec $BACKTRACE --pattern $PATH_TO_PLUGIN/spec/**/*_spec.rb

cache:
  directories:
  - vendor/bundle